# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32b636381e21a24d958087439c1691d621dc508bed7812718559d26e52afb30a1de2669b4965b12eb6d174c340925237e2bae912c445b67003ad1a60f88ef31b

test:
  secret_key_base: 7763427ca42cc81c07f8a212ddea8305e59c9645ae82769add47e7c4c269ec62f2206ae52e8404bf204918b0ff476f57b0a862ee6536b3a699e7be0cb248a398

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
